### ISSUE TITLE
Replace mini with shallow clone packages/core instead

### ISSUE THREAD

**Issue by nanoant** [archmac/bootstrap#1]
As in the title. Unless I am missing something obvious, it would be nice to have bootstrap to pull https://github.com/archmac/packages/tree/master/core instead of maintaining own replica of core packages.

**Comment by lloeki** [comment]
The bootstrap is not useful anymore, it was mostly a hack to get things running and packaged, so I'm not sure it's worth spending much time on it as I mostly kept it for historical purposes.

**Comment by lloeki** [comment]
Touched on that in the updated README:

https://github.com/archmac/bootstrap/tree/ecb583d97f3ebcb93862d619f36ed679b95d3dae#stage-4-build-from-a-repo

Basically the package set is small and it's simpler to try Apple Silicon without the coupling.
